### ISSUE TITLE
Add appropriate license to JsTracker

### ISSUE THREAD

**Issue by claytondaley** [claytondaley/DaleyPiwik#1]
@heiglandreas recently updated [license](https://github.com/heiglandreas/piwik/blob/master/LICENSE) on his code to MIT.

**Comment by heiglandreas** [comment]
well, recently actally was at least 10 months ago :wink: 

There wasn't any other license AFAIK

**Comment by claytondaley** [comment]
My mistake.  The MIT did come through with the code.  I got a notification about rayzor65/rayzor-analytics#1 and just assumed it was the upstream repo for this.
